// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProjectStatus = "NotYetStarted" | "Preparation" | "Bidding" | "Bidded" | "OnGoing" | "Completed" | "Suspended";

export type RequestAddProjectPayment = { project_id: number, billing_date: string, processed_by: string, amount_due: string, amount_paid: number, reference_no: string, payment_date: string, };

export type RequestAddProjects = { project_year: number, project_name: string, project_code: string, project_status: ProjectStatus | null, barangays: Array<number> | null, appropriation: number | null, approved_budget_contact: number | null, contractor_id: number | null, contract_cost: number | null, start_date: string | null, calendar_days: string | null, time_extensions: number | null, target_date: string | null, project_type_id: number | null, project_category_id: number | null, project_sof_id: number | null, project_incharge_id: number | null, sustainable_development_goals: Array<number> | null, sector: Array<number> | null, project_takers_id: number | null, accomplished: number | null, remarks: string | null, prepared_users_id: number | null, };

export type RequestDeleteProjectRemarks = { id: number, user_password: string, };

export type RequestDeleteProjectsPayment = { id: number, user_password: string, };

export type RequestDisposedProjectsById = { id: number, user_password: string, };

export type RequestGenerateProjectsProfile = { id: number, };

export type RequestUpdateProjects = { id: number, project_year: number, project_name: string, project_code: string, project_status: ProjectStatus | null, barangays: Array<number> | null, appropriation: number | null, approved_budget_contact: number | null, contractor_id: number | null, contract_cost: number | null, start_date: string | null, calendar_days: string | null, time_extensions: number | null, target_date: string | null, project_type_id: number | null, project_category_id: number | null, project_sof_id: number | null, project_incharge_id: number | null, sustainable_development_goals: Array<number> | null, sector: Array<number> | null, project_takers_id: number | null, accomplished: number | null, remarks: string | null, prepared_users_id: number | null, };

export type RequestUpsertProjectsInfraCode = { id: number | null, projects_id: number, projects_code: string, };

export type ResponseProjectPayment = { id: number, project_id: number, billing_date: string, processed_by: string, amount_due: string, amount_paid: number, reference_no: string, payment_date: string, };
