// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ResponseSummaryFinancialStatusProjects = { project_name: string, project_code: string, contractor_name: string | null, taker_name: string | null, project_status: string | null, project_start_date: string | null, project_target_date: string | null, project_contract_cost: number | null, project_paid: bigint | null, };

export type ResponseSummaryFinancialStatusProjectsOverview = { data: Array<ResponseSummaryFinancialStatusProjects>, total_records: number, total_contract_cost: bigint, total_paid: bigint, total_balance: bigint, };

export type ResponseSummaryFinancialStatusReports = { total_projects: bigint, total_appropriation: bigint, total_contract_cost: bigint, total_paid: bigint, total_balance: bigint, total_savings: bigint, };

export type ResponseSummaryFinancialStatusReportsOverview = { data_implemented: ResponseSummaryFinancialStatusReports, data_unimplemented: ResponseSummaryFinancialStatusReports, data_suspended: ResponseSummaryFinancialStatusReports, data_summary: ResponseSummaryFinancialStatusReports, };

export type ResponseSummaryImplementationByYear = { project_year: number, project_status: string, total_projects: bigint, total_appropriation: bigint, };

export type ResponseSummaryImplementationByYearFullOverview = { projects_data: Array<ResponseSummaryImplementationByYearOverview>, total_status: number, total_projects: bigint, total_appropriation: bigint, };

export type ResponseSummaryImplementationByYearOverview = { year: number, data: Array<ResponseSummaryImplementationByYear>, };

export type ResponseSummaryListOfProjects = { project_id: number, project_name: string, project_code: string, project_appropriation: number | null, project_bid_date: string | null, project_contract_cost: number | null, contractor_id: number | null, contractor_name: string | null, sof_id: number | null, sof_name: string | null, project_status: string | null, project_accomplished: number | null, project_taker_id: number | null, project_taker_name: string | null, project_year: number, project_remarks: string | null, };

export type ResponseSummaryListOfProjectsOverview = { summary_list_of_reports: Array<ResponseSummaryListOfProjects>, total_records: number, total_appropriation: bigint, total_contract_cost: bigint, };

export type ResponseSummaryProjectSavingsReport = { project_name: string, project_code: string, project_status: string | null, contractor_name: string | null, taker_name: string | null, approved_budget_contract: number | null, appropriation: number | null, contract_cost: number | null, savings: number, };

export type ResponseSummaryProjectSavingsReportOverview = { data: Array<ResponseSummaryProjectSavingsReport>, total_records: number, total_appropriation: bigint, total_abc: bigint, total_contract_cost: bigint, total_savings: bigint, };

export type ResponseSummaryProjectsPerType = { project_type: string, total_projects: bigint, total_appropriation: bigint, };

export type ResponseSummaryProjectsPerTypeOverview = { total_types: number, total_projects: bigint, total_appropriation: bigint, data: Array<ResponseSummaryProjectsPerType>, };

export type ResponseSummarySlippageReport = { project_name: string, contractor_name: string, taker_name: string, start_date: string, target_date: string, days_lapse: number, remarks: string, };

export type ResponseSummarySlippageReportOverview = { data: Array<ResponseSummarySlippageReport>, total_records: number, };
