// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ResponseProjectPayment } from "./Projects";

export type RequestAddBarangay = { name: string, barangay_type: RequestBarangayType | null, is_poblacion: boolean, };

export type RequestAddCategories = { name: string, };

export type RequestAddContractors = { name: string, email_address: string, address_street: string, address_barangay: string, address_municipality: string, address_province: string, about: string | null, contact_full_name: string, contact_position: string, contact_number: string, };

export type RequestAddIncharge = { name: string, };

export type RequestAddSector = { name: string, };

export type RequestAddSourceOfFunds = { name: string, };

export type RequestAddSustainableDevelopmentGoals = { name: string, };

export type RequestAddTakers = { name: string, contact_number: string | null, };

export type RequestAddTypes = { name: string, };

export type RequestBarangayType = "Rural" | "Urban";

export type RequestDeleteBarangay = { id: number, user_password: string, };

export type RequestDeleteCategories = { id: number, user_password: string, };

export type RequestDeleteContractorsById = { id: number, user_password: string, };

export type RequestDeleteIncharge = { id: number, user_password: string, };

export type RequestDeleteSector = { id: number, user_password: string, };

export type RequestDeleteSourceOfFunds = { id: number, user_password: string, };

export type RequestDeleteSustainableDevelopmentGoals = { id: number, user_password: string, };

export type RequestDeleteTakers = { id: number, user_password: string, };

export type RequestDeleteTypes = { id: number, user_password: string, };

export type RequestGenerateProjectsContractors = { id: number, };

export type RequestGetSustainableDevelopmentGoalsById = { id: string, };

export type RequestUpdateBarangay = { id: number, name: string, barangay_type: RequestBarangayType | null, is_poblacion: boolean, };

export type RequestUpdateCategories = { id: number, name: string, };

export type RequestUpdateContractors = { id: number, name: string, email_address: string, address_street: string, address_barangay: string, address_municipality: string, address_province: string, about: string | null, contact_full_name: string, contact_position: string, contact_number: string, };

export type RequestUpdateIncharge = { id: number, name: string, };

export type RequestUpdateSector = { id: number, name: string, };

export type RequestUpdateSourceOfFunds = { id: number, name: string, };

export type RequestUpdateSustainableDevelopmentGoals = { id: number, name: string, };

export type RequestUpdateTakers = { id: number, name: string, contact_number: string | null, };

export type RequestUpdateTypes = { id: number, name: string, };

export type ResponseBarangays = { id: number, name: string, barangay_type: RequestBarangayType | null, is_poblacion: boolean, };

export type ResponseCategories = { id: number, name: string, };

export type ResponseContractors = { id: number, name: string, email_address: string, address_street: string, address_barangay: string, address_municipality: string, address_province: string, about: string | null, contact_full_name: string, contact_position: string, contact_number: string, is_delete: boolean, };

export type ResponseContractorsWithProjects = { contractor: ResponseContractors, projects: Array<ResponseProjectForContractors>, };

export type ResponseIncharge = { id: number, name: string, };

export type ResponsePrepareAllSettings = { s_barangay: Array<ResponseBarangays>, contractors: Array<ResponseContractors>, s_type: Array<ResponseTypes>, s_categories: Array<ResponseCategories>, s_sof: Array<ResponseSourceOfFunds>, s_incharge: Array<ResponseIncharge>, s_sdg: Array<ResponseSustainableDevelopmentGoals>, s_sector: Array<ResponseSector>, s_takers: Array<ResponseTakers>, };

export type ResponseProjectForContractors = { project_id: number, project_name: string, project_code: string, project_status: string | null, project_takers: string | null, project_appropriation: number, project_contract_cost: number, };

export type ResponseProjectInfraCode = { id: number, project_id: number, project_code: string, };

export type ResponseProjectRemarks = { id: number, remarks: string, remarks_date: string, project_id: number, };

export type ResponseProjectRemarksImg = { id: number, remarks_id: number, images_key: string, images_original_name: string, };

export type ResponseProjectsByFund = { projects_id: number, projects_name: string, project_code: string, project_status: string | null, contract_cost: number | null, contractor_id: number | null, contractor_name: string | null, };

export type ResponseProjectsById = { projects_id: number, projects_name: string, projects_code: string, project_year: number, projects_status: string, projects_appropriation: number | null, projects_approved_budget_contract: number | null, projects_accomplished: number | null, projects_remarks: string | null, projects_contract_cost: number | null, projects_start_date: string | null, projects_target_date: string | null, projects_barangay: Array<ResponseBarangays> | null, projects_sdg: Array<ResponseSustainableDevelopmentGoals> | null, projects_sector: Array<ResponseSector> | null, s_types_name: string | null, s_category_name: string | null, s_sof_name: string | null, s_incharge_name: string | null, s_takers_name: string | null, contractor_name: string | null, infra_code: string | null, };

export type ResponseProjectsOverview = { total_projects: bigint, total_unimplemented: bigint, total_preparing: bigint, total_bidded: bigint, total_bidding: bigint, total_ongoing: bigint, total_completed: bigint, };

export type ResponseProjectsSectorWithAppropriation = { name: string, value: number, };

export type ResponseProjectsStatsCategory = { name: string, projects_total: bigint, };

export type ResponseProjectsStatsTypes = { name: string, projects_total: bigint, };

export type ResponseProjectsTop10Appropriation = { id: number, name: string, project_code: string, appropriation: number, };

export type ResponseProjectsTop10Awared = { constructor_id: number, name: string, total_projects: bigint, total_appropriation: bigint | null, };

export type ResponseSector = { id: number, name: string, };

export type ResponseSourceOfFunds = { id: number, name: string, };

export type ResponseSustainableDevelopmentGoals = { id: number, name: string, };

export type ResponseTakers = { id: number, name: string, contact_number: string | null, };

export type ResponseTypes = { id: number, name: string, };

export type ResponseViewProjectsById = { projects_info: ResponseProjectsById, projects_remarks_image: Array<ResponseProjectRemarksImg>, projects_remarks: Array<ResponseProjectRemarks>, projects_payment: Array<ResponseProjectPayment>, };
