// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RequestAddUpdateUserInfoById = { id: number | null, first_name: string, middle_name: string, last_name: string, user_id: number, };

export type RequestAddUser = { email: string, password: string, user_role: number, };

export type RequestDeleteUserById = { id: number, };

export type RequestUpdateUser = { id: number, email: string, password: string | null, user_role: number, };

export type RequestUserLogin = { email: string, password: string, };

export type ResponseAccountInfoForUsersWithFullInfo = { user_info_id: number, user_info_first_name: string, user_info_middle_name: string, user_info_last_name: string, };

export type ResponseLogin = { jwt_token: string, session_id: string, info_id: number | null, info_first_name: string | null, info_middle_name: string | null, info_last_name: string | null, };

export type ResponseUserRoles = { id: number, name: string, };

export type ResponseUsersRolesForUsersWithFullInfo = { role_id: number, role_name: string, };

export type ResponseUsersWithFullInfo = { user_id: number, user_email: string, user_roles: ResponseUsersRolesForUsersWithFullInfo | null, user_info: ResponseAccountInfoForUsersWithFullInfo | null, };

export type ResponseUsersWithRoles = { user_id: number, email: string, user_roles_id: number, user_roles: ResponseUserRoles | null, };
